### ISSUE TITLE
Group lessons in sections

### ISSUE THREAD

**Issue by rotimi-best** [rotimi-best/classroomio#430]
### Feature Description

The ability to group lessons into sections

### Please check the boxes that apply to this feature request.

- [ ] I have searched the existing feature requests to make sure this is not a duplicate.
- [ ] I have provided a detailed description of the requested feature.
- [ ] I have explained the use case or scenario for this feature.
- [ ] I have included any relevant technical details or design suggestions.
- [ ] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by rotimi-best** [comment]
# TODO

- [x] Add new course type for backward compatibilty
- [x] UI for section and lesson on sidebar
- [x] UI for section and lesson on /lessons
- [x] Create section and associate with lesson
- [ ] Re ordering of sections
- [ ] Re ordering of lessons in sections
- [x] Delete section and all lessons
- [ ] Write function that can transition a course to v2 type
